server:
  port: 8082

spring:
  application:
    name: TRACKING-MICROSERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost