
server:
  port: 8083

spring:
  application:
    name: EMAIL-MICROSERVICE
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username: dipanjanmaji45@@gmail.com
    password: acup ysdq ilrv naqi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost