server:
    port: 8081

spring:
    application:
        name: LICENSE-MICROSERVICE

    datasource:
        url: jdbc:mysql://localhost:3306/licensedb?createDatabaseIfNotExist=true
        username: root
        password: 1993
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost